### ISSUE TITLE
CoffeeScript 6 Placeholder Logo

### ISSUE THREAD

**Issue by carlsmith** [coffeescript6/discuss#6]
Obviously, this isn't something we can use seriously. It's just a placeholder logo we can use for our GitHub avatar while we work out what we're doing. It took about 3 minutes, so I wouldn't be bothered if we didn't use it. I was trying to fix my GIMP installation after El Capitan, and needed something to paint. Click it to see a slightly bigger version, and optionally download it.

<a href='https://postimg.org/image/5be9ludy9/' target='_blank'><img src='https://s32.postimg.org/5be9ludy9/coffeescript.png' border='0' alt='postimage'/></a>

**Comment by JimPanic** [comment]
I like the idea, though a more elaborate "6" would work better. 👍

**Comment by ohaz** [comment]
Perhaps use a stylized "6" as the mug?

**Comment by carlsmith** [comment]
Thanks guys. It really was just a quick thing to test that a graphics program was installed and working. I wasn't being modest :)

Once we decide what were doing and have a name for it, then we can see who wants to do a logo. I can do something better than this at least, if no one else offers to help.

**Comment by rattrayalex** [comment]
Nice! I like the direction as well

**Comment by rattrayalex** [comment]
```
                                          ,--.
                                         /  .'
                                        .  / -.
    _____       __  __                  | .-.  '
  / ____|     / _|/ _|                  ' \  |  |
 | |     ___ | |_| |_ ___  ___     .-`` \  `'  / '-.
 | |    / _ \|  _|  _/ _ \/ _ \   (      `----'     )
 | |___| (_) | | | ||  __/  __/   |`-..________ ..-'|
  \_____\___/|_| |_| \___|\___|   |                 |
                                  |                 ;--.
   _____           _       _      |                (__  \
  / ____|         (_)     | |     |                 | )  )
 | (___   ___ _ __ _ _ __ | |_    |                 |/  /
 \___ \ / __| '__| | '_ \| __|    |                 (  /
 ____) | (__| |  | | |_) | |_     |                 |/
|_____/ \___|_|  |_| .__/ \__|    |                 |
                   | |             `-.._________..-'
                   |_|
```

thoughts?

(the 6 came from http://patorjk.com/software/taag/#p=display&f=Ghost&t=6 )

**Comment by JimPanic** [comment]
I like it :)

**Comment by rattrayalex** [comment]
Closing, as one of these is already in the README; future suggestions can be made in the form of PR's.
