### ISSUE TITLE
Merging repos

### ISSUE THREAD

**Issue by GeoffreyBooth** [coffeescript6/discuss#93]
It’s been suggested that we migrate the issues from this repo into the main [jashkenas/coffeescript](https://github.com/jashkenas/coffeescript/) repo. This would keep all this great history in one place, and searchable together. I know there’s a lot of value in having separate repos for feature requests versus bug reports, but until this repo started the main repo handled both, and at this point I think it’s better to keep everything together rather than to try to split up that one. There are also a lot more people following that repo than this one, so the issues here would get more visibility over there.

So unless this idea unleashes a firestorm of opposition, I’ll look into migrating these issues there soon.

**Comment by rattrayalex** [comment]
I would definitely support that. I think this repo has served its purpose and is now probably best used as a historical artifact. 

Not sure the logistics of disabling new issues, maybe just use an issue template telling people to file at the main repo instead? And then just manually lock any open threads?
